### ISSUE TITLE
Unexpected interaction between starlette and pydantic dependencies

### ISSUE THREAD

**Issue by quaterneon** [Kludex/starlette#1082] opened 2020-10-30 21:25 UTC
### Checklist

- [X] The bug is reproducible against the latest release and/or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

We had a project that is running starlette version 0.13.8. We recently added pydantic 1.7. This completely broke CORS handling in our app. 

We don't know why this interaction happens, but we've traced to a dependency of pydantic. Pydantic also installs email_validator 1.1.1, which in turn installs dnspython 2.0.0. Uninstalling dnspython fixes the CORS handling. 

### To reproduce

Setup a starlette app with CORS enabled, and install the latest pydantic version as well (verify that it ends up adding dnspython to the environment). See CORS break. Uninstall dnspython. See CORS fixed.

### Expected behavior

I would expect starlette to play nice with pydantic.

### Actual behavior

Installing pydantic with starlette causes all CORS checks to fail.

### Debugging material

All API calls fail on CORS checks.

### Environment

- OS: macOS, tiangolo gunicorn/uvicorn/starlette docker image
- Python version: 3.7
- Starlette version: 0.13.8

### Additional context

EDIT: Discovered that pydantic recommends https://pypi.org/project/datamodel-code-generator/ for codegen, which installs the pydantic[email], and this is what actually results in dnspython getting installed.

**Comment by euri10** [comment] 2020-10-31 09:05
I tested 2 things: 

1. added pydantic in the venv used for developing starlette, ran tests, in particular the middlewares ones and there is no issue
2. wrote a simple app with cors middleware enabled, using pydantic in the venv as well, as described in your issue and I have no cors problem, the headers are set correctly, no issues

So far I can't reproduce so you'd have to 
1. give us more insights on giving a minimum reproducible app and 
2. describe a little bit more clearly what you mean by "cors break"

**Comment by quaterneon** [comment] 2020-11-03 22:36
Hi! So base pydantic is fine, it's only once you install pydantic[email] do things start going awry. The best check is to see whether the library dnspython got installed in the venv.

By "make CORS break" I mean that every single request to the API started to get rejected on CORS-based grounds (I'm not entirely clear on whether all origins were being disallowed or whether no headers were set though). 

RE: other reproducibility data, here was our app definition (I pruned out unrelated things)

```
from starlette.applications import Starlette
from starlette.routing import Route
from starlette.requests import Request
from starlette.responses import JSONResponse, HTMLResponse

async def home(request: Request):
    return HTMLResponse("Hello, World!", status_code=200)

routes = [
    Route("/", endpoint=home, methods=["GET"])
]

origins = [
    "https://localhost:3000",
    "http://localhost:3000",
    "OUR PRODUCTION FRONT-END HOST",
]
middleware = [
    Middleware(
        CORSMiddleware,
        allow_origins=origins,
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["Authorization"],
    )
]

app = Starlette(
    routes=routes,
    middleware=middleware,
)
```

Also, a **subset** of installed python packages from a commit to this app where no CORS checks from our front-end would succeed:
```
alembic==1.4.3
asyncpg==0.21.0
attrs==20.2.0
certifi==2020.6.20
cryptography==3.2.1
databases==0.3.2
datamodel-code-generator==0.6.0
dnspython==2.0.0
email-validator==1.1.1
gunicorn==20.0.4
h11==0.9.0
html5lib==1.1
httptools==0.1.1
idna==2.10
importlib-metadata==2.0.0
itsdangerous==1.1.0
jeepney==0.4.3
Jinja2==2.11.2
keyring==20.0.1
lockfile==0.12.2
Mako==1.1.3
MarkupSafe==1.1.1
msgpack==1.0.0
networkx==2.5
oauthlib==3.1.0
openapi-spec-validator==0.2.9
pathspec==0.8.0
pexpect==4.8.0
pkginfo==1.6.1
poetry==1.0.10
prance==0.19.0
promise==2.3
psycopg2-binary==2.8.6
ptyprocess==0.6.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
pydantic==1.7
pylev==1.3.0
pyparsing==2.4.7
pyrsistent==0.17.3
PySnooper==0.4.2
python-dateutil==2.8.1
python-editor==1.0.4
python-multipart==0.0.5
pytz==2020.1
PyYAML==5.3.1
regex==2020.10.23
rsa==4.6
Rx==1.6.1
SecretStorage==3.1.2
semver==2.13.0
Shapely==1.7.1
six==1.15.0
SQLAlchemy==1.3.20
starlette==0.13.8
threadpoolctl==2.1.0
toml==0.10.1
tomlkit==0.5.11
typed-ast==1.4.1
ujson==4.0.1
urllib3==1.25.11
uvicorn==0.11.8
uvloop==0.14.0
webencodings==0.5.1
websocket-client==0.57.0
websockets==8.1
wrapt==1.12.1
zipp==3.4.0
```

And a subset of the dependencies specified in pyproject.toml:
```
[tool.poetry.dependencies]
python = "^3.7"
alembic = "^1.4.2"
pytz = "^2020.1"
starlette = {extras = ["full"], version = "^0.13.7"}
databases = {extras = ["postgresql"], version = "^0.3.2"}
uvicorn = "^0.11.8"
sqlalchemy = "^1.3.18"
pydantic = "^1.7"
datamodel-code-generator = "^0.6.0"
```

**Comment by euri10** [comment] 2020-11-04 07:37
cant reproduce sorry

all tests pass fine with installing `pydantic[email]`

on top of that, using your snippet application, it seems to me that the cors is working ok simulating a preflight request with curl (see https://stackoverflow.com/questions/12173990/how-can-you-debug-a-cors-request-with-curl),

```
curl -H "Origin: http://localhost:3000" \
  -H "Access-Control-Request-Method: POST" \
  -H "Access-Control-Request-Headers: Authorization" \
  -X OPTIONS --verbose \
http://localhost:8000
* Expire in 0 ms for 6 (transfer 0x5626f72dff50)
* Expire in 1 ms for 1 (transfer 0x5626f72dff50)
* Expire in 0 ms for 1 (transfer 0x5626f72dff50)
* Expire in 1 ms for 1 (transfer 0x5626f72dff50)
* Expire in 0 ms for 1 (transfer 0x5626f72dff50)
* Expire in 0 ms for 1 (transfer 0x5626f72dff50)
* Expire in 1 ms for 1 (transfer 0x5626f72dff50)
* Expire in 0 ms for 1 (transfer 0x5626f72dff50)
* Expire in 0 ms for 1 (transfer 0x5626f72dff50)
* Expire in 1 ms for 1 (transfer 0x5626f72dff50)
* Expire in 0 ms for 1 (transfer 0x5626f72dff50)
* Expire in 0 ms for 1 (transfer 0x5626f72dff50)
* Expire in 1 ms for 1 (transfer 0x5626f72dff50)
* Expire in 0 ms for 1 (transfer 0x5626f72dff50)
* Expire in 0 ms for 1 (transfer 0x5626f72dff50)
* Expire in 1 ms for 1 (transfer 0x5626f72dff50)
* Expire in 0 ms for 1 (transfer 0x5626f72dff50)
* Expire in 0 ms for 1 (transfer 0x5626f72dff50)
* Expire in 1 ms for 1 (transfer 0x5626f72dff50)
* Expire in 0 ms for 1 (transfer 0x5626f72dff50)
* Expire in 0 ms for 1 (transfer 0x5626f72dff50)
* Expire in 1 ms for 1 (transfer 0x5626f72dff50)
* Expire in 0 ms for 1 (transfer 0x5626f72dff50)
* Expire in 0 ms for 1 (transfer 0x5626f72dff50)
* Expire in 1 ms for 1 (transfer 0x5626f72dff50)
* Expire in 0 ms for 1 (transfer 0x5626f72dff50)
* Expire in 0 ms for 1 (transfer 0x5626f72dff50)
* Expire in 1 ms for 1 (transfer 0x5626f72dff50)
* Expire in 0 ms for 1 (transfer 0x5626f72dff50)
* Expire in 0 ms for 1 (transfer 0x5626f72dff50)
* Expire in 1 ms for 1 (transfer 0x5626f72dff50)
* Expire in 0 ms for 1 (transfer 0x5626f72dff50)
* Expire in 0 ms for 1 (transfer 0x5626f72dff50)
* Expire in 1 ms for 1 (transfer 0x5626f72dff50)
* Expire in 0 ms for 1 (transfer 0x5626f72dff50)
* Expire in 0 ms for 1 (transfer 0x5626f72dff50)
* Expire in 1 ms for 1 (transfer 0x5626f72dff50)
* Expire in 0 ms for 1 (transfer 0x5626f72dff50)
* Expire in 0 ms for 1 (transfer 0x5626f72dff50)
* Expire in 1 ms for 1 (transfer 0x5626f72dff50)
* Expire in 0 ms for 1 (transfer 0x5626f72dff50)
* Expire in 0 ms for 1 (transfer 0x5626f72dff50)
* Expire in 1 ms for 1 (transfer 0x5626f72dff50)
* Expire in 0 ms for 1 (transfer 0x5626f72dff50)
* Expire in 0 ms for 1 (transfer 0x5626f72dff50)
* Expire in 1 ms for 1 (transfer 0x5626f72dff50)
* Expire in 0 ms for 1 (transfer 0x5626f72dff50)
* Expire in 0 ms for 1 (transfer 0x5626f72dff50)
* Expire in 1 ms for 1 (transfer 0x5626f72dff50)
* Expire in 0 ms for 1 (transfer 0x5626f72dff50)
* Expire in 0 ms for 1 (transfer 0x5626f72dff50)
* Expire in 1 ms for 1 (transfer 0x5626f72dff50)
* Expire in 0 ms for 1 (transfer 0x5626f72dff50)
* Expire in 0 ms for 1 (transfer 0x5626f72dff50)
* Expire in 1 ms for 1 (transfer 0x5626f72dff50)
* Expire in 0 ms for 1 (transfer 0x5626f72dff50)
* Expire in 0 ms for 1 (transfer 0x5626f72dff50)
* Expire in 1 ms for 1 (transfer 0x5626f72dff50)
* Expire in 0 ms for 1 (transfer 0x5626f72dff50)
* Expire in 0 ms for 1 (transfer 0x5626f72dff50)
* Expire in 1 ms for 1 (transfer 0x5626f72dff50)
* Expire in 0 ms for 1 (transfer 0x5626f72dff50)
* Expire in 0 ms for 1 (transfer 0x5626f72dff50)
* Expire in 1 ms for 1 (transfer 0x5626f72dff50)
* Expire in 0 ms for 1 (transfer 0x5626f72dff50)
* Expire in 0 ms for 1 (transfer 0x5626f72dff50)
* Expire in 0 ms for 1 (transfer 0x5626f72dff50)
*   Trying ::1...
* TCP_NODELAY set
* Expire in 150000 ms for 3 (transfer 0x5626f72dff50)
* Expire in 200 ms for 4 (transfer 0x5626f72dff50)
* connect to ::1 port 8000 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Expire in 150000 ms for 3 (transfer 0x5626f72dff50)
* Connected to localhost (127.0.0.1) port 8000 (#0)
> OPTIONS / HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.64.0
> Accept: */*
> Origin: http://localhost:3000
> Access-Control-Request-Method: POST
> Access-Control-Request-Headers: Authorization
> 
< HTTP/1.1 200 OK
< date: Wed, 04 Nov 2020 07:31:29 GMT
< server: uvicorn
< vary: Origin
< access-control-allow-methods: DELETE, GET, OPTIONS, PATCH, POST, PUT
< access-control-max-age: 600
< access-control-allow-headers: Accept, Accept-Language, Authorization, Content-Language, Content-Type
< access-control-allow-origin: http://localhost:3000
< content-length: 2
< content-type: text/plain; charset=utf-8
< 
* Connection #0 to host localhost left intact
OK%  
```

best way to proceed would be for you to write a test that fails with the libraries you think are posing an issue (which I dont see how it could since they're not called at all on that topic, but hey, I could easily be overlooking something simple)

reading your 1st issue I notice you're in a docker environment, I'd take that out of the equation as a sanity check 1st

until then I'm gonna close it, feel free to reopen if you feel you can add more to help us reproduce.

**Closed as completed by euri10** 2020-11-04 07:37 UTC
