### ISSUE TITLE
Error in app startup makes test runner hang

### ISSUE THREAD

**Issue by blueyed** [Kludex/starlette#431] opened 2019-03-09 18:36 UTC
With an error during app startup, pytest will hang after exiting.

```python
@app.on_event("startup")
async def startup():
    assert 0
```

`Ctrl-C` then shows this:
```
=================================== 1 error in 0.34 seconds ====================================
^CException ignored in: <module 'threading' from '/usr/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 1273, in _shutdown
    t.join()
  File "/usr/lib/python3.7/threading.py", line 1032, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

This appears to be related to the test client's lifespan task, but have not really investigated much: https://github.com/blueyed/starlette/blob/8297495d4eb08842b0dc36a1d9bc89f7246ad449/starlette/testclient.py#L409

**Comment by blueyed** [comment] 2019-03-09 18:51
Traceback to the error for reference:
```
  …/Vcs/pytest/src/_pytest/fixtures.py(778)call_fixture_func()
-> res = next(it)
  …/project/tests/conftest.py(27)client()
-> with TestClient(app) as test_client:
  …/Vcs/starlette/starlette/testclient.py(410)__enter__()
-> loop.run_until_complete(self.wait_startup())
  /usr/lib/python3.7/asyncio/base_events.py(571)run_until_complete()
-> self.run_forever()
  /usr/lib/python3.7/asyncio/base_events.py(539)run_forever()
-> self._run_once()
  /usr/lib/python3.7/asyncio/base_events.py(1775)_run_once()
-> handle._run()
  /usr/lib/python3.7/asyncio/events.py(88)_run()
-> self._context.run(self._callback, *self._args)
  …/Vcs/starlette/starlette/testclient.py(420)lifespan()
-> await inner(self.receive_queue.get, self.send_queue.put)
  …/Vcs/starlette/starlette/routing.py(478)asgi()
-> await self.startup()
  …/Vcs/starlette/starlette/routing.py(461)startup()
-> await handler()
> …/app.py(51)startup()
-> assert 0
```

**Comment by blueyed** [comment] 2019-04-17 22:33
I've noticed this also with a normal error after `database.connect()`:

```python
database = databases.Database(dburl)

@app.on_event("startup")
async def startup():
    await database.connect()
    # this works around it (from `database.disconnect`):
    # await database._global_transaction.__aexit__()
    assert 0
```

So I wonder if the "shutdown" signal/event should be called maybe always, or some other even "startuperror" or similar, but sounds like overkill.

In any way it should be clarified in the docs probably: https://github.com/encode/starlette/blob/765c38f221af76254acf1f0b2b42360e76c496a4/docs/events.md#registering-events.

**Comment by blueyed** [comment] 2019-04-17 22:35
(These are two issues, but with the same outcome)

**Comment by blueyed** [comment] 2019-04-17 23:38
Just found this about "startup failed" in lifespan: https://github.com/django/asgiref/issues/78#issuecomment-469170445 - relevant?

**Comment by septatrix** [comment] 2021-10-30 02:01
I also observed this when trying to stop my app which had an infinite loop in a startup hook. I was unable to stop the app using <kbd>Ctrl</kbd>+<kbd>C</kbd> und had to revert to `SIGKILL`. It feels like these hooks are tried in an infinite loop until they all pass without any exceptions. Instead they should probably result in the whole app failing and exiting.

**Comment by Kludex** [comment] 2022-01-28 23:16
I can't reproduce this on Starlette 0.18.0 and Pytest 6.2.5.

I'm closing this issue.

**Closed as completed by Kludex** 2022-01-28 23:16 UTC
